experimento_wisard_1:
	python3 classifier.py --file /home/jolima/Documentos/multilabel-classification/dataset/kaggle_dataset.csv --n_iter 3 --min_ram 3 --max_ram 5 --min_ter 3 --max_ter 5 --n_sample 10 

preprocessamento_tfidf:
	python3 preprocessing_tfidf.py --file /home/jolima/Documentos/multilabel-classification/dataset/kaggle_dataset.csv --n_sample 10
	
preprocessamento_doc2vec:
	python3 preprocessing_doc2vec.py --file /home/jolima/Documentos/multilabel-classification/dataset/kaggle_dataset.csv --n_sample 5